version: '3'

services:
  db:
    image: mysql

  web:
    build: .
    command: python run.py
    volumes:
      - .:/app
    image: jsingh/eeazycrm
    ports:
      - "5000:5000"
    depends_on:
      - db