---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.hub.docker.com/aph1d/craft-bike
    username: "{{ docker_user }}"
    password: "{{ docker_password }}"
    reauthorize: true

- name: Pull Docker image
  docker_image:
    name: registry.hub.docker.com/aph1d/craft-bike:latest
    state: present
    force_source: true
    source: pull
  async: 1800
  poll: 5

- name: Run Docker container
  docker_container:
    name: craft-bike-app
    image: registry.hub.docker.com/aph1d/craft-bike:latest
    state: started
    restart_policy: always
    restart: true
    networks:
      - name: otel_otel
    # network_mode: host
    ports:
      - 8003:8003
    volumes:
      - /usr/craftbike/images/avatars:/serwis_crm_app/serwis_crm/static/profile_imgs:rw
    env:
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
      AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION  }}"
      MYSQL_HOST: "{{ MYSQL_HOST }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_PORT: "{{ MYSQL_PORT }}"
      MYSQL_DB_NAME: "{{ MYSQL_DB_NAME }}"
      SECRET_KEY: "{{ SECRET_KEY }}"
      GITHUB_SHA: "{{ GITHUB_SHA }}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_SERVICE_NAME: craftbike-app
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=production
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
