---
- name: Main Deployment Playbook
  hosts: vps-e9084b50.vps.ovh.net
  become: true
  tasks:
    - name: Deploy docker app contianer
      include_tasks: deploy_docker_container.yml
    - name: Install/update nginx
      include_tasks: nginx.yml
