---
- name: Main Deployment Playbook
  hosts: srv21.mikr.us
  become: true
  tasks:
    - name: Deploy docker app contianer
      include_tasks: deploy_docker_container.yml
    - name: Install/update nginx
      include_tasks: nginx.yml
