---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: registry.hub.docker.com/aph1d/craft-bike
    username: "{{ docker_user }}"
    password: "{{ docker_password }}"
    reauthorize: true

- name: Pull Docker image
  docker_image:
    name: registry.hub.docker.com/aph1d/craft-bike:{{ git_commit }}
    source: pull

- name: Run Docker container
  docker_container:
    name: craft-bike-app
    image: registry.hub.docker.com/aph1d/craft-bike:{{ git_commit }}
    state: present
    restart_policy: always
    recreate: true
    ports:
      - 8003:8003
    env:
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
      AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION  }}"
      MYSQL_HOST: "mysql.mikr.us"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_PORT: "3306"
      MYSQL_DB_NAME: "{{ MYSQL_DB_NAME }}"
      SECRET_KEY: "{{ SECRET_KEY }}"
