---
  - name: Check if Nginx is installed
    become: true
    command: "/bin/which nginx"
    register: nginx_installed
    ignore_errors: true
  - name: Install Nginx if not installed
    apt:
      name: nginx
      state: present
    when: nginx_installed.rc != 0
    become: true
  - name: Update Nginx configuration
    template:
      src: templates/nginx.conf.j2  # Path to your custom configuration template
      dest: /etc/nginx/nginx.conf
    become: true
  - name: Create web directory if it doesn't exist
    file:
      path: /var/www/html
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
  - name: Copy index.html to web server
    copy:
      src: ../home_page/index.html
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: '0644'
      backup: true
    notify: restart nginx
  - name: restart nginx
    service:
      name: nginx
      state: restarted
