
name: Docker Build, Push to ECR and deploy
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  push_to_ecr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        aws-region: eu-central-1

    - name: Get current branch name
      id: get_branch_name
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/heads/}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.login-ecr.outputs.registry }}/craft-bike-ecr:${{ steps.get_branch_name.outputs.branch_name }}.${{ github.sha }}
        build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION=eu-central-1

