
name: Docker Build, Push to Docker Hub and deploy
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get current branch name
      id: get_branch_name
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/heads/}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: aph1d/craft-bike:${{ steps.get_branch_name.outputs.branch_name }}.${{ github.sha }}, aph1d/craft-bike:latest
  deploy_docker_container_using_ansible:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup SSH 
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts
      - name: Run ansible script
        shell: bash 
        run: |
          service ssh status
          cd ansible
          ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -u ${{secrets.ANSIBLE_DEPLOY_USER}} -i inventory.yml -e "docker_user=${{ secrets.DOCKERHUB_USERNAME }}" -e "docker_password=${{ secrets.DOCKERHUB_TOKEN }}" -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -e "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" -e "MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME}}" -e "MYSQL_USER=${{ secrets.MYSQL_USER }}" -e "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" deployment.yml
