
name: Docker Build and Push to ECR
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  push_to_ecr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get current branch name
      id: get_branch_name
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/heads/}
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        platforms: linux/amd64
        tags: craft-bike-ecr:${{ steps.get_branch_name.outputs.branch_name }}.${{ github.sha }}
        build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_DB_NAME=serwis-crm

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        image: craft-bike-ecr:${{ steps.get_branch_name.outputs.branch_name }}.${{ github.sha }}